POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZ5c2NoZXIiLCJpZCI6IjY4NWIwOGQzNjc4YmFlMGIzN2IwMTYwNCIsImlhdCI6MTc1MDgwMDIxNSwiZXhwIjoxNzUwODAzODE1fQ.N6ba9WdX8ThpsJDSjcXSBi0NgV-6-48L-Ems07IDQLk

{
    "title": "HOORAY I DID IT!!",
    "author": "FB Blue",
    "url": "www.420.com",
    "likes": 420
}